sudo: false

dist: bionic

language:
    - c++

# Blacklist
branches:
  only:
    - master

# Install dependencies
addons:
  apt:
    packages:
      - g++
      - doxygen
      - graphviz
      - libboost-filesystem-dev
      - cmake

before_install:
  - sudo apt-get update
  - sudo apt-get install libboost-system-dev

install:
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}
  - travis_retry wget --no-check-certificate https://cmake.org/files/v3.3/cmake-3.3.2-Linux-x86_64.tar.gz
  - tar -xvf cmake-3.3.2-Linux-x86_64.tar.gz > /dev/null
  - mv cmake-3.3.2-Linux-x86_64 cmake-install
  - PATH=${DEPS_DIR}/cmake-install:${DEPS_DIR}/cmake-install/bin:$PATH
  - cd ${TRAVIS_BUILD_DIR}

# Build your code e.g. by calling make
before_script:
  - pwd
  - mkdir build_dir && cd build_dir
  - cmake -DCMAKE_BUILD_TYPE=Release
          -DETISS_BUILD_MANUAL_DOC=ON 
          -DCMAKE_INSTALL_PREFIX:PATH= `pwd`/installed 
          ..    
  - make
  - make doc
  - sudo make install
  - echo "retrieving token"
  - echo $GITHUB_TOKEN
  - echo "$PATH"

# Generate and deploy documentation
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: build_dir/doc/html
  github_token: $GITHUB_TOKEN
  on:
    branch: master
 
# building example
script:
  - pwd
  - cd ../examples/SW/riscv/
  - pwd
  - sudo mkdir build 
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug ..
  - make
  - mkdir build && cd build
  - cmake ..
  - make
  - cd ..
  - ./run_helper.sh path/to/target/binary
