sudo: false

dist: bionic

language:
    - c++

# Blacklist
branches:
  only:
    - master

# Install dependencies
addons:
  apt:
    packages:
      - g++
      - doxygen
      - graphviz
      - libboost-filesystem-dev

before_install:
  - sudo apt-get update
  - sudo apt-get install libboost-system-dev
  - sudo apt-get install build-essential git
  - sudo apt install clang

install:
  - echo ${TRAVIS_BUILD_DIR}
  - mkdir -p ${TRAVIS_BUILD_DIR}/deps/cmake
  - wget https://cmake.org/files/v3.16/cmake-3.16.2-Linux-x86_64.sh # getting Cmake version 3.16.2
  - sh cmake-3.16.2-Linux-x86_64.sh --prefix=${TRAVIS_BUILD_DIR}/deps/cmake --exclude-subdir #save cmake package into directory
  - PATH=${TRAVIS_BUILD_DIR}/deps/cmake:${TRAVIS_BUILD_DIR}/deps/cmake/bin:$PATH #hiding old version of Cmake
  - cd ${TRAVIS_BUILD_DIR}

# Build your code e.g. by calling make
before_script:
  - mkdir build_dir && cd build_dir
  - echo `pwd`
  - cmake -DCMAKE_BUILD_TYPE=Release -DETISS_BUILD_MANUAL_DOC=ON -DCMAKE_INSTALL_PREFIX:PATH=`pwd`/installed ..
  - make
  - make doc
  - make install
  - echo "retrieving token"
  - echo $GITHUB_TOKEN
  - echo "$PATH"  
  
script:
  - mkdir build
  - cd build
  - cmake ..
  - make
   
 

# Generate and deploy documentation
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: build_dir/doc/html
  github_token: $GITHUB_TOKEN
  on:
    branch: master

