sudo: false

dist: bionic

language:
    - c++

# Blacklist
branches:
  only:
    - master

# Install dependencies
addons:
  apt:
    packages:
      - g++
      - doxygen
      - graphviz
      - libboost-filesystem-dev
      - cmake

before_install:
  - sudo apt-get update
  - sudo apt-get install libboost-system-dev

install:
  - mkdir -p ${TRAVIS_BUILD_DIR}/deps/cmake
  - wget https://cmake.org/files/v3.16/cmake-3.16.2-Linux-x86_64.sh
  - sh cmake-3.16.2-Linux-x86_64.sh --prefix=${TRAVIS_BUILD_DIR}/deps/cmake --exclude-subdir
  - PATH=${TRAVIS_BUILD_DIR}/deps/cmake:${TRAVIS_BUILD_DIR}/deps/cmake/bin:$PATH

# Build your code e.g. by calling make
before_script:
  - pwd
  - mkdir build_dir && cd build_dir
  - cmake -DCMAKE_BUILD_TYPE=Release
          -DETISS_BUILD_MANUAL_DOC=ON 
          -DCMAKE_INSTALL_PREFIX:PATH= ${TRAVIS_BUILD_DIR}/build_dir/installed
          -DBUILD_SOURCE_DOCUMENTATION=ON
          ..    
  - make
  - make doc
  - sudo make install
  - echo "retrieving token"
  - echo $GITHUB_TOKEN
  - echo "$PATH"
  
 script:
  - pwd
  - cd ../examples/SW/riscv/
  - pwd
  - sudo mkdir build 
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug ..
  - make
  - mkdir build && cd build
  - cmake ..
  - make
  - cd ..
  - ./run_helper.sh path/to/target/binary 

# Generate and deploy documentation
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: build_dir/doc/html
  github_token: $GITHUB_TOKEN
  on:
    branch: master
 

