sudo: false

dist: bionic

language:
    - c++

# Blacklist
branches:
  only:
    - master

# Install dependencies
addons:
  apt:
    packages:
      - g++
      - doxygen
      - graphviz
      - libboost-filesystem-dev

before_install:
  - sudo apt-get update
  - sudo apt-get install libboost-system-dev

install:
  - mkdir -p ${TRAVIS_BUILD_DIR}/deps/cmake
  - wget https://cmake.org/files/v3.16/cmake-3.16.2-Linux-x86_64.sh
  - sh cmake-3.16.2-Linux-x86_64.sh --prefix=${TRAVIS_BUILD_DIR}/deps/cmake --exclude-subdir
  - PATH=${TRAVIS_BUILD_DIR}/deps/cmake:${TRAVIS_BUILD_DIR}/deps/cmake/bin:$PATH

# Build your code e.g. by calling make
script:
  - mkdir build_dir && cd build_dir
  - cmake -DETISS_BUILD_MANUAL_DOC=ON ..
  - cmake -DCMAKE_INSTALL_PREFIX:PATH= `pwd`/installed ..
  - make
  - make doc
  - sudo make install
  - echo "retrieving token"
  - echo $GITHUB_TOKEN
  - echo "$PATH"

# Generate and deploy documentation
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: build_dir/doc/html
  github_token: $GITHUB_TOKEN
  on:
    branch: master
 
# building example
after_deploy:
  - cd ../SW/<or1k>|<riscv>/
  - mkdir build && cd build
  - cmake ..
  - make
  - mkdir build && cd build
  - cmake ..
  - make
  - cd ..
  - ${TRAVIS_BUILD_DIR}/examples/bare_etiss_processor/run_helper.sh.in
  - ${TRAVIS_BUILD_DIR}/examples/bare_etiss_processor/run_helper.sh.in ELFFILE tgdb
