sudo: false

dist: bionic

language:
    - c++

# Blacklist
branches:
  only:
    - master

# Install dependencies
addons:
  apt:
    packages:
      - g++
      - doxygen
      - graphviz
      - libboost-filesystem-dev

before_install:
  - sudo apt-get update
  - sudo apt-get install libboost-system-dev
  - sudo apt-get install gdbserver
  - sudo apt-get install build-essential git
  - sudo apt install clang

install:
  - echo ${TRAVIS_BUILD_DIR}
  - mkdir -p ${TRAVIS_BUILD_DIR}/deps/cmake
  - mkdir -p ${TRAVIS_BUILD_DIR}/deps/toolchain
  - wget https://cmake.org/files/v3.16/cmake-3.16.2-Linux-x86_64.sh # getting Cmake version 3.16.2
  - sh cmake-3.16.2-Linux-x86_64.sh --prefix=${TRAVIS_BUILD_DIR}/deps/cmake --exclude-subdir #save cmake package into directory
  - wget https://static.dev.sifive.com/dev-tools/riscv64-unknown-elf-gcc-8.3.0-2019.08.0-x86_64-linux-ubuntu14.tar.gz
  - tar -zxf riscv64-unknown-elf-gcc-8.3.0-2019.08.0-x86_64-linux-ubuntu14.tar.gz --directory ${TRAVIS_BUILD_DIR}/deps/toolchain
  - PATH=${TRAVIS_BUILD_DIR}/deps/cmake:${TRAVIS_BUILD_DIR}/deps/cmake/bin:${TRAVIS_BUILD_DIR}/deps/toolchain:$PATH #hiding old version of Cmake
  - PATH=${TRAVIS_BUILD_DIR}/deps/toolchain:${TRAVIS_BUILD_DIR}/deps/toolchain/bin:${TRAVIS_BUILD_DIR}/deps/toolchain:$PATH
  - cd ${TRAVIS_BUILD_DIR}

# Build your code e.g. by calling make
before_script:
  - mkdir build_dir && cd build_dir
  - echo `pwd`
  - cmake -DCMAKE_BUILD_TYPE=Release -DETISS_BUILD_MANUAL_DOC=ON -DCMAKE_INSTALL_PREFIX:PATH=`pwd`/installed ..
  - make
  - make doc
  - make install
  - echo "retrieving token"
  - echo $GITHUB_TOKEN
  - echo "$PATH"  
  
script:
  - echo $home
  - cd ${TRAVIS_BUILD_DIR}/build_dir/installed/examples/SW/riscv
  - mkdir build
  - cd build
  - cmake -DRISCV_ELF_GCC_PREFIX=${TRAVIS_BUILD_DIR}/deps/toolchain/riscv64-unknown-elf-gcc-8.3.0-2019.08.0-x86_64-linux-ubuntu14 -DRISCV_ELF_GCC_BASENAME=riscv64-unknown-elf ..
  - make
  - make all
  - cd ${TRAVIS_BUILD_DIR}/build_dir/installed/examples/bare_etiss_processor
  - mkdir build && cd build
  - cmake ..
  - make
  - cd ..
  - ./run_helper.sh ${TRAVIS_BUILD_DIR}/build_dir/installed/examples/SW/riscv/build/riscv_example tgdb
   
 

# Generate and deploy documentation
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: build_dir/doc/html
  github_token: $GITHUB_TOKEN
  on:
    branch: master

