sudo: false

dist: bionic

language:
    - c++

# Blacklist
branches:
  only:
    - master

# Install dependencies
addons:
  apt:
    packages:
      - g++
      - doxygen
      - graphviz
      - libboost-filesystem-dev
      - cmake

before_install:
  - sudo apt-get update
  - sudo apt-get install clang
  - sudo apt-get install libboost-system-dev

install:
  - echo ${TRAVIS_BUILD_DIR}
  - mkdir -p ${TRAVIS_BUILD_DIR}/deps/cmake
  - travis_retry wget https://cmake.org/files/v3.16/cmake-3.16.2-Linux-x86_64.sh # getting Cmake version 3.16.2
  - sh cmake-3.16.2-Linux-x86_64.sh --prefix=${TRAVIS_BUILD_DIR}/deps/cmake --exclude-subdir #save cmake package into directory
  - echo $PATH
  - PATH=${TRAVIS_BUILD_DIR}/deps/cmake:${TRAVIS_BUILD_DIR}/deps/cmake/bin:$PATH #hiding old version of Cmake

# Build your code e.g. by calling make
before_script:
  - mkdir build_dir && cd build_dir
  - cmake -DCMAKE_BUILD_TYPE=Release
          -DETISS_BUILD_MANUAL_DOC=ON 
          -DCMAKE_INSTALL_PREFIX:PATH= `pwd`/installed ..  #Install ETISS in to `pwd`/installed by running CMakelist from ../ETISS.buid_dir
  - make
  - make doc
  - sudo make install
  - echo "retrieving token"
  - echo $GITHUB_TOKEN
  - echo "$PATH"  
  
script:
  - cd ${TRAVIS_BUILD_DIR}/build_dir/installed/examples/SW/riscv/
  - mkdir build 
  - cd build
  - cmake ..
  - make
  - cd ${TRAVIS_BUILD_DIR}/examples/bare_etiss_processor 
  - mkdir build && cd build
  - cmake ..
  - make
  - cd ..
  - ./run_helper.sh path/to/target/binary     
   
 

# Generate and deploy documentation
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: build_dir/doc/html
  github_token: $GITHUB_TOKEN
  on:
    branch: master

