sudo: false

dist: bionic

language:
    - c++

# Install dependencies
addons:
  apt:
    packages:
      - g++
      - doxygen
      - graphviz
      - libboost-system-dev
      - libboost-filesystem-dev
      - libtinfo-dev
      - zlib1g-dev

#before_install:
  #- sudo apt-get install gdbserver
  #- sudo apt-get install build-essential git
  #- sudo apt install clang

install:
  - mkdir -p ${TRAVIS_BUILD_DIR}/deps
  - Dep_dir="${TRAVIS_BUILD_DIR}/deps"
#  - cd ${Dep_dir}
  - mkdir -p ${Dep_dir}/cmake #directory for Cmake version 3.16.2
  - mkdir -p ${Dep_dir}/toolchain #directly for Riscv64 toolchain
  - mkdir -p ${Dep_dir}/JIT #directory for LLVM 
  - wget https://cmake.org/files/v3.16/cmake-3.16.2-Linux-x86_64.sh # getting Cmake version 3.16.2 (works)
  - Cmake_version16="cmake-3.16.2-Linux-x86_64.sh"
  - sh ${Cmake_version16} --prefix=${TRAVIS_BUILD_DIR}/deps/cmake --exclude-subdir #save cmake package into directory
  - wget https://static.dev.sifive.com/dev-tools/riscv64-unknown-elf-gcc-8.3.0-2019.08.0-x86_64-linux-ubuntu14.tar.gz #Install sifive riscv64 package
  - RISC_V64="riscv64-unknown-elf-gcc-8.3.0-2019.08.0-x86_64-linux-ubuntu14.tar.gz"
  - tar -zxf ${RISC_V64} --directory ${Dep_dir}/toolchain #extract file to directory
  - travis_retry wget https://releases.llvm.org/7.0.1/clang+llvm-7.0.1-x86_64-linux-gnu-ubuntu-18.04.tar.xz #install LLVM 7.0.1
  - lvm_701="clang+llvm-7.0.1-x86_64-linux-gnu-ubuntu-18.04.tar.xz"
  - tar -xf ${lvm_701} --directory ${Dep_dir}/JIT #extract LLVM to directory
  - PATH=${Dep_dir}/cmake:${Dep_dir}/cmake/bin:$PATH #hiding old version of Cmake

  
# Build ETISS your code e.g. by calling make
before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build_dir && cd build_dir
  - cmake -DLLVM_DIR=${Dep_dir}/LLVM/${llvm_701}/lib/cmake/llvm -DCMAKE_BUILD_TYPE=Release -DETISS_BUILD_MANUAL_DOC=ON -DCMAKE_INSTALL_PREFIX:PATH=`pwd`/installed ..
  - make
  - make doc
  - make install

script:
  - cd ${TRAVIS_BUILD_DIR}/build_dir/installed/examples/SW/riscv
  - mkdir build
  - cd build
  - cmake -DRISCV_ELF_GCC_PREFIX=${Dep_dir}/toolchain/${RISC_V64} -DRISCV_ELF_GCC_BASENAME=riscv64-unknown-elf ..
  - make
  - cd ${TRAVIS_BUILD_DIR}/build_dir/installed/examples/SW/riscv_cpp
  - mkdir build
  - cd build
  - cmake -DRISCV_ELF_GCC_PREFIX=${Dep_dir}/toolchain/${RISC_V64} -DRISCV_ELF_GCC_BASENAME=riscv64-unknown-elf ..
  - make 
  - cd ${TRAVIS_BUILD_DIR}/build_dir/installed/examples/bare_etiss_processor
  - mkdir build && cd build
  - cmake ..
  - make
  - cd ..
  - ./run_helper.sh ${TRAVIS_BUILD_DIR}/build_dir/installed/examples/SW/riscv/build/riscv_example 
  - ./run_helper.sh ${TRAVIS_BUILD_DIR}/build_dir/installed/examples/SW/riscv_cpp/build/riscv_example GCC 
   
 

# Generate and deploy documentation
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: build_dir/doc/html
  github_token: $GITHUB_TOKEN
  on:
    branch: master

