ETISS 0.8.0: /home/travis/build/chunyulok/etiss/src/jitlibs/fp_funcs/fp_functions.cpp File Reference
fp_functions.cpp File Reference
#include "softfloat_orig.h"
#include "internals.h"
#include "specialize.h"
#include <limits>
Functions
uint32_t fget_flags ()
uint32_t fadd_s (uint32_t v1, uint32_t v2, uint8_t mode)
uint32_t fsub_s (uint32_t v1, uint32_t v2, uint8_t mode)
uint32_t fmul_s (uint32_t v1, uint32_t v2, uint8_t mode)
uint32_t fdiv_s (uint32_t v1, uint32_t v2, uint8_t mode)
uint32_t fsqrt_s (uint32_t v1, uint8_t mode)
uint32_t fcmp_s (uint32_t v1, uint32_t v2, uint32_t op)
uint32_t fcvt_s (uint32_t v1, uint32_t op, uint8_t mode)
uint32_t fmadd_s (uint32_t v1, uint32_t v2, uint32_t v3, uint32_t op, uint8_t mode)
uint32_t fsel_s (uint32_t v1, uint32_t v2, uint32_t op)
uint32_t fclass_s (uint32_t v1)
uint32_t fconv_d2f (uint64_t v1, uint8_t mode)
uint64_t fconv_f2d (uint32_t v1, uint8_t mode)
uint64_t fadd_d (uint64_t v1, uint64_t v2, uint8_t mode)
uint64_t fsub_d (uint64_t v1, uint64_t v2, uint8_t mode)
uint64_t fmul_d (uint64_t v1, uint64_t v2, uint8_t mode)
uint64_t fdiv_d (uint64_t v1, uint64_t v2, uint8_t mode)
uint64_t fsqrt_d (uint64_t v1, uint8_t mode)
uint64_t fcmp_d (uint64_t v1, uint64_t v2, uint32_t op)
uint64_t fcvt_d (uint64_t v1, uint32_t op, uint8_t mode)
uint64_t fmadd_d (uint64_t v1, uint64_t v2, uint64_t v3, uint32_t op, uint8_t mode)
uint64_t fsel_d (uint64_t v1, uint64_t v2, uint32_t op)
uint64_t fclass_d (uint64_t v1)
uint64_t fcvt_32_64 (uint32_t v1, uint32_t op, uint8_t mode)
uint32_t fcvt_64_32 (uint64_t v1, uint32_t op, uint8_t mode)
uint32_t unbox_s (uint64_t v)
Variables
const uint8_t rmm_map []
const uint32_t quiet_nan32 =0x7fC00000
Function Documentation
fadd_d()
uint64_t fadd_d (uint64_t v1, uint64_t v2, uint8_t mode)
Definition at line 233 of file fp_functions.cpp.
References defaultNaNF32UI, f64_add(), quiet_nan32, rmm_map, softfloat_exceptionFlags, softfloat_isSigNaNF32UI, softfloat_roundingMode, and float64_t::v.
fadd_s()
uint32_t fadd_s (uint32_t v1, uint32_t v2, uint8_t mode)
Definition at line 58 of file fp_functions.cpp.
References f32_add(), rmm_map, softfloat_exceptionFlags, softfloat_roundingMode, and float32_t::v.
fclass_d()
uint64_t fclass_d (uint64_t v1)
Definition at line 363 of file fp_functions.cpp.
References expF64UI, ui64_f64::f, fracF64UI, isNaNF64UI, signF64UI, softfloat_isSigNaNF64UI, and ui64_f64::ui.
fclass_s()
uint32_t fclass_s (uint32_t v1)
Definition at line 182 of file fp_functions.cpp.
References expF32UI, ui32_f32::f, fracF32UI, isNaNF32UI, signF32UI, softfloat_isSigNaNF32UI, and ui32_f32::ui.
fcmp_d()
uint64_t fcmp_d (uint64_t v1, uint64_t v2, uint32_t op)
Definition at line 275 of file fp_functions.cpp.
References defaultNaNF64UI, f64_eq(), f64_le(), f64_lt(), quiet_nan32, softfloat_exceptionFlags, softfloat_flag_invalid, softfloat_isSigNaNF64UI, and softfloat_raiseFlags().
fcmp_s()
uint32_t fcmp_s (uint32_t v1, uint32_t v2, uint32_t op)
Definition at line 98 of file fp_functions.cpp.
References defaultNaNF32UI, f32_eq(), f32_le(), f32_lt(), quiet_nan32, softfloat_exceptionFlags, softfloat_flag_invalid, softfloat_isSigNaNF32UI, and softfloat_raiseFlags().
fconv_d2f()
uint32_t fconv_d2f (uint64_t v1, uint8_t mode)
Definition at line 211 of file fp_functions.cpp.
References defaultNaNF32UI, defaultNaNF64UI, f64_to_f32(), rmm_map, softfloat_roundingMode, and float32_t::v.
fconv_f2d()
uint64_t fconv_f2d (uint32_t v1, uint8_t mode)
Definition at line 222 of file fp_functions.cpp.
References defaultNaNF32UI, defaultNaNF64UI, f32_to_f64(), rmm_map, softfloat_roundingMode, and float64_t::v.
fcvt_32_64()
uint64_t fcvt_32_64 (uint32_t v1, uint32_t op, uint8_t mode)
Definition at line 392 of file fp_functions.cpp.
References f32_to_i64(), f32_to_ui64(), i32_to_f64(), rmm_map, softfloat_exceptionFlags, ui32_to_f64(), and float64_t::v.
fcvt_64_32()
uint32_t fcvt_64_32 (uint64_t v1, uint32_t op, uint8_t mode)
Definition at line 411 of file fp_functions.cpp.
References f64_to_i32(), f64_to_ui32(), i64_to_f32(), rmm_map, softfloat_exceptionFlags, ui64_to_f32(), and float32_t::v.
fcvt_d()
uint64_t fcvt_d (uint64_t v1, uint32_t op, uint8_t mode)
Definition at line 305 of file fp_functions.cpp.
References f64_to_i64(), f64_to_ui64(), i64_to_f64(), rmm_map, softfloat_exceptionFlags, ui64_to_f64(), and float64_t::v.
fcvt_s()
uint32_t fcvt_s (uint32_t v1, uint32_t op, uint8_t mode)
Definition at line 128 of file fp_functions.cpp.
References f32_to_i32(), f32_to_ui32(), i32_to_f32(), rmm_map, softfloat_exceptionFlags, ui32_to_f32(), and float32_t::v.
fdiv_d()
uint64_t fdiv_d (uint64_t v1, uint64_t v2, uint8_t mode)
Definition at line 259 of file fp_functions.cpp.
References f64_div(), rmm_map, softfloat_exceptionFlags, softfloat_roundingMode, and float64_t::v.
fdiv_s()
uint32_t fdiv_s (uint32_t v1, uint32_t v2, uint8_t mode)
Definition at line 82 of file fp_functions.cpp.
References f32_div(), rmm_map, softfloat_exceptionFlags, softfloat_roundingMode, and float32_t::v.
fget_flags()
uint32_t fget_flags ()
Definition at line 54 of file fp_functions.cpp.
References softfloat_exceptionFlags.
fmadd_d()
uint64_t fmadd_d (uint64_t v1, uint64_t v2, uint64_t v3, uint32_t op, uint8_t mode)
Definition at line 328 of file fp_functions.cpp.
References rmm_map, softfloat_exceptionFlags, softfloat_mulAddF64(), softfloat_roundingMode, and float64_t::v.
fmadd_s()
uint32_t fmadd_s (uint32_t v1, uint32_t v2, uint32_t v3, uint32_t op, uint8_t mode)
Definition at line 151 of file fp_functions.cpp.
References rmm_map, softfloat_exceptionFlags, softfloat_mulAddF32(), softfloat_roundingMode, and float32_t::v.
fmul_d()
uint64_t fmul_d (uint64_t v1, uint64_t v2, uint8_t mode)
Definition at line 251 of file fp_functions.cpp.
References f64_mul(), rmm_map, softfloat_exceptionFlags, softfloat_roundingMode, and float64_t::v.
fmul_s()
uint32_t fmul_s (uint32_t v1, uint32_t v2, uint8_t mode)
Definition at line 74 of file fp_functions.cpp.
References f32_mul(), rmm_map, softfloat_exceptionFlags, softfloat_roundingMode, and float32_t::v.
fsel_d()
uint64_t fsel_d (uint64_t v1, uint64_t v2, uint32_t op)
Definition at line 337 of file fp_functions.cpp.
References defaultNaNF64UI, f64_lt(), softfloat_exceptionFlags, softfloat_flag_invalid, softfloat_isSigNaNF64UI, and softfloat_raiseFlags().
fsel_s()
uint32_t fsel_s (uint32_t v1, uint32_t v2, uint32_t op)
Definition at line 160 of file fp_functions.cpp.
References defaultNaNF32UI, f32_lt(), softfloat_exceptionFlags, softfloat_flag_invalid, softfloat_isSigNaNF32UI, and softfloat_raiseFlags().
fsqrt_d()
uint64_t fsqrt_d (uint64_t v1, uint8_t mode)
Definition at line 267 of file fp_functions.cpp.
References f64_sqrt(), rmm_map, softfloat_exceptionFlags, softfloat_roundingMode, and float64_t::v.
fsqrt_s()
uint32_t fsqrt_s (uint32_t v1, uint8_t mode)
Definition at line 90 of file fp_functions.cpp.
References f32_sqrt(), rmm_map, softfloat_exceptionFlags, softfloat_roundingMode, and float32_t::v.
fsub_d()
uint64_t fsub_d (uint64_t v1, uint64_t v2, uint8_t mode)
Definition at line 243 of file fp_functions.cpp.
References f64_sub(), rmm_map, softfloat_exceptionFlags, softfloat_roundingMode, and float64_t::v.
fsub_s()
uint32_t fsub_s (uint32_t v1, uint32_t v2, uint8_t mode)
Definition at line 66 of file fp_functions.cpp.
References f32_sub(), rmm_map, softfloat_exceptionFlags, softfloat_roundingMode, and float32_t::v.
unbox_s()
uint32_t unbox_s (uint64_t v)
Definition at line 433 of file fp_functions.cpp.
Variable Documentation
quiet_nan32
const uint32_t quiet_nan32 =0x7fC00000
Definition at line 52 of file fp_functions.cpp.
Referenced by fadd_d(), fcmp_d(), and fcmp_s().
rmm_map
const uint8_t rmm_map[]
Initial value:
= {
        softfloat_round_near_even ,
        softfloat_round_minMag,
        softfloat_round_min,
        softfloat_round_max,
        softfloat_round_near_maxMag ,
        softfloat_round_max,
        softfloat_round_max,
        softfloat_round_max,
}
Definition at line 41 of file fp_functions.cpp.
Referenced by fadd_d(), fadd_s(), fconv_d2f(), fconv_f2d(), fcvt_32_64(), fcvt_64_32(), fcvt_d(), fcvt_s(), fdiv_d(), fdiv_s(), fmadd_d(), fmadd_s(), fmul_d(), fmul_s(), fsqrt_d(), fsqrt_s(), fsub_d(), and fsub_s().