ETISS 0.8.0: /home/travis/build/chunyulok/etiss/src/jitlibs/softfloat/softfloat_orig.h File Reference
softfloat_orig.h File Reference
#include <stdbool.h>
#include <stdint.h>
#include "softfloat_types.h"
Macros
#define THREAD_LOCAL
Enumerations
enum { softfloat_tininess_beforeRounding = 0, softfloat_tininess_afterRounding = 1 }
enum {
softfloat_round_near_even = 0, softfloat_round_minMag = 1, softfloat_round_min = 2, softfloat_round_max = 3,
softfloat_round_near_maxMag = 4, softfloat_round_odd = 6
}
enum {
softfloat_flag_inexact = 1, softfloat_flag_underflow = 2, softfloat_flag_overflow = 4, softfloat_flag_infinite = 8,
softfloat_flag_invalid = 16
}
Functions
void softfloat_raiseFlags (uint_fast8_t)
float16_t ui32_to_f16 (uint32_t)
float32_t ui32_to_f32 (uint32_t)
float64_t ui32_to_f64 (uint32_t)
void ui32_to_extF80M (uint32_t, extFloat80_t *)
void ui32_to_f128M (uint32_t, float128_t *)
float16_t ui64_to_f16 (uint64_t)
float32_t ui64_to_f32 (uint64_t)
float64_t ui64_to_f64 (uint64_t)
void ui64_to_extF80M (uint64_t, extFloat80_t *)
void ui64_to_f128M (uint64_t, float128_t *)
float16_t i32_to_f16 (int32_t)
float32_t i32_to_f32 (int32_t)
float64_t i32_to_f64 (int32_t)
void i32_to_extF80M (int32_t, extFloat80_t *)
void i32_to_f128M (int32_t, float128_t *)
float16_t i64_to_f16 (int64_t)
float32_t i64_to_f32 (int64_t)
float64_t i64_to_f64 (int64_t)
void i64_to_extF80M (int64_t, extFloat80_t *)
void i64_to_f128M (int64_t, float128_t *)
uint_fast32_t f16_to_ui32 (float16_t, uint_fast8_t, bool)
uint_fast64_t f16_to_ui64 (float16_t, uint_fast8_t, bool)
int_fast32_t f16_to_i32 (float16_t, uint_fast8_t, bool)
int_fast64_t f16_to_i64 (float16_t, uint_fast8_t, bool)
uint_fast32_t f16_to_ui32_r_minMag (float16_t, bool)
uint_fast64_t f16_to_ui64_r_minMag (float16_t, bool)
int_fast32_t f16_to_i32_r_minMag (float16_t, bool)
int_fast64_t f16_to_i64_r_minMag (float16_t, bool)
float32_t f16_to_f32 (float16_t)
float64_t f16_to_f64 (float16_t)
void f16_to_extF80M (float16_t, extFloat80_t *)
void f16_to_f128M (float16_t, float128_t *)
float16_t f16_roundToInt (float16_t, uint_fast8_t, bool)
float16_t f16_add (float16_t, float16_t)
float16_t f16_sub (float16_t, float16_t)
float16_t f16_mul (float16_t, float16_t)
float16_t f16_mulAdd (float16_t, float16_t, float16_t)
float16_t f16_div (float16_t, float16_t)
float16_t f16_rem (float16_t, float16_t)
float16_t f16_sqrt (float16_t)
bool f16_eq (float16_t, float16_t)
bool f16_le (float16_t, float16_t)
bool f16_lt (float16_t, float16_t)
bool f16_eq_signaling (float16_t, float16_t)
bool f16_le_quiet (float16_t, float16_t)
bool f16_lt_quiet (float16_t, float16_t)
bool f16_isSignalingNaN (float16_t)
uint_fast32_t f32_to_ui32 (float32_t, uint_fast8_t, bool)
uint_fast64_t f32_to_ui64 (float32_t, uint_fast8_t, bool)
int_fast32_t f32_to_i32 (float32_t, uint_fast8_t, bool)
int_fast64_t f32_to_i64 (float32_t, uint_fast8_t, bool)
uint_fast32_t f32_to_ui32_r_minMag (float32_t, bool)
uint_fast64_t f32_to_ui64_r_minMag (float32_t, bool)
int_fast32_t f32_to_i32_r_minMag (float32_t, bool)
int_fast64_t f32_to_i64_r_minMag (float32_t, bool)
float16_t f32_to_f16 (float32_t)
float64_t f32_to_f64 (float32_t)
void f32_to_extF80M (float32_t, extFloat80_t *)
void f32_to_f128M (float32_t, float128_t *)
float32_t f32_roundToInt (float32_t, uint_fast8_t, bool)
float32_t f32_add (float32_t, float32_t)
float32_t f32_sub (float32_t, float32_t)
float32_t f32_mul (float32_t, float32_t)
float32_t f32_mulAdd (float32_t, float32_t, float32_t)
float32_t f32_div (float32_t, float32_t)
float32_t f32_rem (float32_t, float32_t)
float32_t f32_sqrt (float32_t)
bool f32_eq (float32_t, float32_t)
bool f32_le (float32_t, float32_t)
bool f32_lt (float32_t, float32_t)
bool f32_eq_signaling (float32_t, float32_t)
bool f32_le_quiet (float32_t, float32_t)
bool f32_lt_quiet (float32_t, float32_t)
bool f32_isSignalingNaN (float32_t)
uint_fast32_t f64_to_ui32 (float64_t, uint_fast8_t, bool)
uint_fast64_t f64_to_ui64 (float64_t, uint_fast8_t, bool)
int_fast32_t f64_to_i32 (float64_t, uint_fast8_t, bool)
int_fast64_t f64_to_i64 (float64_t, uint_fast8_t, bool)
uint_fast32_t f64_to_ui32_r_minMag (float64_t, bool)
uint_fast64_t f64_to_ui64_r_minMag (float64_t, bool)
int_fast32_t f64_to_i32_r_minMag (float64_t, bool)
int_fast64_t f64_to_i64_r_minMag (float64_t, bool)
float16_t f64_to_f16 (float64_t)
float32_t f64_to_f32 (float64_t)
void f64_to_extF80M (float64_t, extFloat80_t *)
void f64_to_f128M (float64_t, float128_t *)
float64_t f64_roundToInt (float64_t, uint_fast8_t, bool)
float64_t f64_add (float64_t, float64_t)
float64_t f64_sub (float64_t, float64_t)
float64_t f64_mul (float64_t, float64_t)
float64_t f64_mulAdd (float64_t, float64_t, float64_t)
float64_t f64_div (float64_t, float64_t)
float64_t f64_rem (float64_t, float64_t)
float64_t f64_sqrt (float64_t)
bool f64_eq (float64_t, float64_t)
bool f64_le (float64_t, float64_t)
bool f64_lt (float64_t, float64_t)
bool f64_eq_signaling (float64_t, float64_t)
bool f64_le_quiet (float64_t, float64_t)
bool f64_lt_quiet (float64_t, float64_t)
bool f64_isSignalingNaN (float64_t)
uint_fast32_t extF80M_to_ui32 (const extFloat80_t *, uint_fast8_t, bool)
uint_fast64_t extF80M_to_ui64 (const extFloat80_t *, uint_fast8_t, bool)
int_fast32_t extF80M_to_i32 (const extFloat80_t *, uint_fast8_t, bool)
int_fast64_t extF80M_to_i64 (const extFloat80_t *, uint_fast8_t, bool)
uint_fast32_t extF80M_to_ui32_r_minMag (const extFloat80_t *, bool)
uint_fast64_t extF80M_to_ui64_r_minMag (const extFloat80_t *, bool)
int_fast32_t extF80M_to_i32_r_minMag (const extFloat80_t *, bool)
int_fast64_t extF80M_to_i64_r_minMag (const extFloat80_t *, bool)
float16_t extF80M_to_f16 (const extFloat80_t *)
float32_t extF80M_to_f32 (const extFloat80_t *)
float64_t extF80M_to_f64 (const extFloat80_t *)
void extF80M_to_f128M (const extFloat80_t *, float128_t *)
void extF80M_roundToInt (const extFloat80_t *, uint_fast8_t, bool, extFloat80_t *)
void extF80M_add (const extFloat80_t *, const extFloat80_t *, extFloat80_t *)
void extF80M_sub (const extFloat80_t *, const extFloat80_t *, extFloat80_t *)
void extF80M_mul (const extFloat80_t *, const extFloat80_t *, extFloat80_t *)
void extF80M_div (const extFloat80_t *, const extFloat80_t *, extFloat80_t *)
void extF80M_rem (const extFloat80_t *, const extFloat80_t *, extFloat80_t *)
void extF80M_sqrt (const extFloat80_t *, extFloat80_t *)
bool extF80M_eq (const extFloat80_t *, const extFloat80_t *)
bool extF80M_le (const extFloat80_t *, const extFloat80_t *)
bool extF80M_lt (const extFloat80_t *, const extFloat80_t *)
bool extF80M_eq_signaling (const extFloat80_t *, const extFloat80_t *)
bool extF80M_le_quiet (const extFloat80_t *, const extFloat80_t *)
bool extF80M_lt_quiet (const extFloat80_t *, const extFloat80_t *)
bool extF80M_isSignalingNaN (const extFloat80_t *)
uint_fast32_t f128M_to_ui32 (const float128_t *, uint_fast8_t, bool)
uint_fast64_t f128M_to_ui64 (const float128_t *, uint_fast8_t, bool)
int_fast32_t f128M_to_i32 (const float128_t *, uint_fast8_t, bool)
int_fast64_t f128M_to_i64 (const float128_t *, uint_fast8_t, bool)
uint_fast32_t f128M_to_ui32_r_minMag (const float128_t *, bool)
uint_fast64_t f128M_to_ui64_r_minMag (const float128_t *, bool)
int_fast32_t f128M_to_i32_r_minMag (const float128_t *, bool)
int_fast64_t f128M_to_i64_r_minMag (const float128_t *, bool)
float16_t f128M_to_f16 (const float128_t *)
float32_t f128M_to_f32 (const float128_t *)
float64_t f128M_to_f64 (const float128_t *)
void f128M_to_extF80M (const float128_t *, extFloat80_t *)
void f128M_roundToInt (const float128_t *, uint_fast8_t, bool, float128_t *)
void f128M_add (const float128_t *, const float128_t *, float128_t *)
void f128M_sub (const float128_t *, const float128_t *, float128_t *)
void f128M_mul (const float128_t *, const float128_t *, float128_t *)
void f128M_mulAdd (const float128_t *, const float128_t *, const float128_t *, float128_t *)
void f128M_div (const float128_t *, const float128_t *, float128_t *)
void f128M_rem (const float128_t *, const float128_t *, float128_t *)
void f128M_sqrt (const float128_t *, float128_t *)
bool f128M_eq (const float128_t *, const float128_t *)
bool f128M_le (const float128_t *, const float128_t *)
bool f128M_lt (const float128_t *, const float128_t *)
bool f128M_eq_signaling (const float128_t *, const float128_t *)
bool f128M_le_quiet (const float128_t *, const float128_t *)
bool f128M_lt_quiet (const float128_t *, const float128_t *)
bool f128M_isSignalingNaN (const float128_t *)
Variables
THREAD_LOCAL uint_fast8_t softfloat_detectTininess
THREAD_LOCAL uint_fast8_t softfloat_roundingMode
THREAD_LOCAL uint_fast8_t softfloat_exceptionFlags
THREAD_LOCAL uint_fast8_t extF80_roundingPrecision
Macro Definition Documentation
THREAD_LOCAL
#define THREAD_LOCAL
Definition at line 54 of file softfloat_orig.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
softfloat_tininess_beforeRounding
softfloat_tininess_afterRounding
Definition at line 61 of file softfloat_orig.h.
anonymous enum
anonymous enum
Enumerator
softfloat_round_near_even
softfloat_round_minMag
softfloat_round_min
softfloat_round_max
softfloat_round_near_maxMag
softfloat_round_odd
Definition at line 71 of file softfloat_orig.h.
anonymous enum
anonymous enum
Enumerator
softfloat_flag_inexact
softfloat_flag_underflow
softfloat_flag_overflow
softfloat_flag_infinite
softfloat_flag_invalid
Definition at line 84 of file softfloat_orig.h.
Function Documentation
extF80M_add()
void extF80M_add (const extFloat80_t * , const extFloat80_t * , extFloat80_t *)
extF80M_div()
void extF80M_div (const extFloat80_t * , const extFloat80_t * , extFloat80_t *)
extF80M_eq()
bool extF80M_eq (const extFloat80_t * , const extFloat80_t *)
extF80M_eq_signaling()
bool extF80M_eq_signaling (const extFloat80_t * , const extFloat80_t *)
extF80M_isSignalingNaN()
bool extF80M_isSignalingNaN (const extFloat80_t *)
extF80M_le()
bool extF80M_le (const extFloat80_t * , const extFloat80_t *)
extF80M_le_quiet()
bool extF80M_le_quiet (const extFloat80_t * , const extFloat80_t *)
extF80M_lt()
bool extF80M_lt (const extFloat80_t * , const extFloat80_t *)
extF80M_lt_quiet()
bool extF80M_lt_quiet (const extFloat80_t * , const extFloat80_t *)
extF80M_mul()
void extF80M_mul (const extFloat80_t * , const extFloat80_t * , extFloat80_t *)
extF80M_rem()
void extF80M_rem (const extFloat80_t * , const extFloat80_t * , extFloat80_t *)
extF80M_roundToInt()
void extF80M_roundToInt (const extFloat80_t * , uint_fast8_t , bool , extFloat80_t *)
extF80M_sqrt()
void extF80M_sqrt (const extFloat80_t * , extFloat80_t *)
extF80M_sub()
void extF80M_sub (const extFloat80_t * , const extFloat80_t * , extFloat80_t *)
extF80M_to_f128M()
void extF80M_to_f128M (const extFloat80_t * , float128_t *)
extF80M_to_f16()
float16_t extF80M_to_f16 (const extFloat80_t *)
extF80M_to_f32()
float32_t extF80M_to_f32 (const extFloat80_t *)
extF80M_to_f64()
float64_t extF80M_to_f64 (const extFloat80_t *)
extF80M_to_i32()
int_fast32_t extF80M_to_i32 (const extFloat80_t * , uint_fast8_t , bool)
extF80M_to_i32_r_minMag()
int_fast32_t extF80M_to_i32_r_minMag (const extFloat80_t * , bool)
extF80M_to_i64()
int_fast64_t extF80M_to_i64 (const extFloat80_t * , uint_fast8_t , bool)
extF80M_to_i64_r_minMag()
int_fast64_t extF80M_to_i64_r_minMag (const extFloat80_t * , bool)
extF80M_to_ui32()
uint_fast32_t extF80M_to_ui32 (const extFloat80_t * , uint_fast8_t , bool)
extF80M_to_ui32_r_minMag()
uint_fast32_t extF80M_to_ui32_r_minMag (const extFloat80_t * , bool)
extF80M_to_ui64()
uint_fast64_t extF80M_to_ui64 (const extFloat80_t * , uint_fast8_t , bool)
extF80M_to_ui64_r_minMag()
uint_fast64_t extF80M_to_ui64_r_minMag (const extFloat80_t * , bool)
f128M_add()
void f128M_add (const float128_t * , const float128_t * , float128_t *)
f128M_div()
void f128M_div (const float128_t * , const float128_t * , float128_t *)
f128M_eq()
bool f128M_eq (const float128_t * , const float128_t *)
f128M_eq_signaling()
bool f128M_eq_signaling (const float128_t * , const float128_t *)
f128M_isSignalingNaN()
bool f128M_isSignalingNaN (const float128_t *)
f128M_le()
bool f128M_le (const float128_t * , const float128_t *)
f128M_le_quiet()
bool f128M_le_quiet (const float128_t * , const float128_t *)
f128M_lt()
bool f128M_lt (const float128_t * , const float128_t *)
f128M_lt_quiet()
bool f128M_lt_quiet (const float128_t * , const float128_t *)
f128M_mul()
void f128M_mul (const float128_t * , const float128_t * , float128_t *)
f128M_mulAdd()
void f128M_mulAdd (const float128_t * , const float128_t * , const float128_t * , float128_t *)
f128M_rem()
void f128M_rem (const float128_t * , const float128_t * , float128_t *)
f128M_roundToInt()
void f128M_roundToInt (const float128_t * , uint_fast8_t , bool , float128_t *)
f128M_sqrt()
void f128M_sqrt (const float128_t * , float128_t *)
f128M_sub()
void f128M_sub (const float128_t * , const float128_t * , float128_t *)
f128M_to_extF80M()
void f128M_to_extF80M (const float128_t * , extFloat80_t *)
f128M_to_f16()
float16_t f128M_to_f16 (const float128_t *)
f128M_to_f32()
float32_t f128M_to_f32 (const float128_t *)
f128M_to_f64()
float64_t f128M_to_f64 (const float128_t *)
f128M_to_i32()
int_fast32_t f128M_to_i32 (const float128_t * , uint_fast8_t , bool)
f128M_to_i32_r_minMag()
int_fast32_t f128M_to_i32_r_minMag (const float128_t * , bool)
f128M_to_i64()
int_fast64_t f128M_to_i64 (const float128_t * , uint_fast8_t , bool)
f128M_to_i64_r_minMag()
int_fast64_t f128M_to_i64_r_minMag (const float128_t * , bool)
f128M_to_ui32()
uint_fast32_t f128M_to_ui32 (const float128_t * , uint_fast8_t , bool)
f128M_to_ui32_r_minMag()
uint_fast32_t f128M_to_ui32_r_minMag (const float128_t * , bool)
f128M_to_ui64()
uint_fast64_t f128M_to_ui64 (const float128_t * , uint_fast8_t , bool)
f128M_to_ui64_r_minMag()
uint_fast64_t f128M_to_ui64_r_minMag (const float128_t * , bool)
f16_add()
float16_t f16_add (float16_t , float16_t)
f16_div()
float16_t f16_div (float16_t , float16_t)
f16_eq()
bool f16_eq (float16_t , float16_t)
f16_eq_signaling()
bool f16_eq_signaling (float16_t , float16_t)
f16_isSignalingNaN()
bool f16_isSignalingNaN (float16_t)
f16_le()
bool f16_le (float16_t , float16_t)
f16_le_quiet()
bool f16_le_quiet (float16_t , float16_t)
f16_lt()
bool f16_lt (float16_t , float16_t)
f16_lt_quiet()
bool f16_lt_quiet (float16_t , float16_t)
f16_mul()
float16_t f16_mul (float16_t , float16_t)
f16_mulAdd()
float16_t f16_mulAdd (float16_t , float16_t , float16_t)
f16_rem()
float16_t f16_rem (float16_t , float16_t)
f16_roundToInt()
float16_t f16_roundToInt (float16_t , uint_fast8_t , bool)
f16_sqrt()
float16_t f16_sqrt (float16_t)
f16_sub()
float16_t f16_sub (float16_t , float16_t)
f16_to_extF80M()
void f16_to_extF80M (float16_t , extFloat80_t *)
f16_to_f128M()
void f16_to_f128M (float16_t , float128_t *)
f16_to_f32()
float32_t f16_to_f32 (float16_t)
f16_to_f64()
float64_t f16_to_f64 (float16_t)
f16_to_i32()
int_fast32_t f16_to_i32 (float16_t , uint_fast8_t , bool)
f16_to_i32_r_minMag()
int_fast32_t f16_to_i32_r_minMag (float16_t , bool)
f16_to_i64()
int_fast64_t f16_to_i64 (float16_t , uint_fast8_t , bool)
f16_to_i64_r_minMag()
int_fast64_t f16_to_i64_r_minMag (float16_t , bool)
f16_to_ui32()
uint_fast32_t f16_to_ui32 (float16_t , uint_fast8_t , bool)
f16_to_ui32_r_minMag()
uint_fast32_t f16_to_ui32_r_minMag (float16_t , bool)
f16_to_ui64()
uint_fast64_t f16_to_ui64 (float16_t , uint_fast8_t , bool)
f16_to_ui64_r_minMag()
uint_fast64_t f16_to_ui64_r_minMag (float16_t , bool)
f32_add()
float32_t f32_add (float32_t , float32_t)
Referenced by fadd_s().
f32_div()
float32_t f32_div (float32_t , float32_t)
Referenced by fdiv_s().
f32_eq()
bool f32_eq (float32_t , float32_t)
Referenced by fcmp_s().
f32_eq_signaling()
bool f32_eq_signaling (float32_t , float32_t)
f32_isSignalingNaN()
bool f32_isSignalingNaN (float32_t)
f32_le()
bool f32_le (float32_t , float32_t)
Referenced by fcmp_s().
f32_le_quiet()
bool f32_le_quiet (float32_t , float32_t)
f32_lt()
bool f32_lt (float32_t , float32_t)
Referenced by fcmp_s(), and fsel_s().
f32_lt_quiet()
bool f32_lt_quiet (float32_t , float32_t)
f32_mul()
float32_t f32_mul (float32_t , float32_t)
Referenced by fmul_s().
f32_mulAdd()
float32_t f32_mulAdd (float32_t , float32_t , float32_t)
f32_rem()
float32_t f32_rem (float32_t , float32_t)
f32_roundToInt()
float32_t f32_roundToInt (float32_t , uint_fast8_t , bool)
f32_sqrt()
float32_t f32_sqrt (float32_t)
Referenced by fsqrt_s().
f32_sub()
float32_t f32_sub (float32_t , float32_t)
Referenced by fsub_s().
f32_to_extF80M()
void f32_to_extF80M (float32_t , extFloat80_t *)
f32_to_f128M()
void f32_to_f128M (float32_t , float128_t *)
f32_to_f16()
float16_t f32_to_f16 (float32_t)
f32_to_f64()
float64_t f32_to_f64 (float32_t)
Referenced by fconv_f2d().
f32_to_i32()
int_fast32_t f32_to_i32 (float32_t , uint_fast8_t , bool)
Referenced by fcvt_s().
f32_to_i32_r_minMag()
int_fast32_t f32_to_i32_r_minMag (float32_t , bool)
f32_to_i64()
int_fast64_t f32_to_i64 (float32_t , uint_fast8_t , bool)
Referenced by fcvt_32_64().
f32_to_i64_r_minMag()
int_fast64_t f32_to_i64_r_minMag (float32_t , bool)
f32_to_ui32()
uint_fast32_t f32_to_ui32 (float32_t , uint_fast8_t , bool)
Referenced by fcvt_s().
f32_to_ui32_r_minMag()
uint_fast32_t f32_to_ui32_r_minMag (float32_t , bool)
f32_to_ui64()
uint_fast64_t f32_to_ui64 (float32_t , uint_fast8_t , bool)
Referenced by fcvt_32_64().
f32_to_ui64_r_minMag()
uint_fast64_t f32_to_ui64_r_minMag (float32_t , bool)
f64_add()
float64_t f64_add (float64_t , float64_t)
Referenced by fadd_d().
f64_div()
float64_t f64_div (float64_t , float64_t)
Referenced by fdiv_d().
f64_eq()
bool f64_eq (float64_t , float64_t)
Referenced by fcmp_d().
f64_eq_signaling()
bool f64_eq_signaling (float64_t , float64_t)
f64_isSignalingNaN()
bool f64_isSignalingNaN (float64_t)
f64_le()
bool f64_le (float64_t , float64_t)
Referenced by fcmp_d().
f64_le_quiet()
bool f64_le_quiet (float64_t , float64_t)
f64_lt()
bool f64_lt (float64_t , float64_t)
Referenced by fcmp_d(), and fsel_d().
f64_lt_quiet()
bool f64_lt_quiet (float64_t , float64_t)
f64_mul()
float64_t f64_mul (float64_t , float64_t)
Referenced by fmul_d().
f64_mulAdd()
float64_t f64_mulAdd (float64_t , float64_t , float64_t)
f64_rem()
float64_t f64_rem (float64_t , float64_t)
f64_roundToInt()
float64_t f64_roundToInt (float64_t , uint_fast8_t , bool)
f64_sqrt()
float64_t f64_sqrt (float64_t)
Referenced by fsqrt_d().
f64_sub()
float64_t f64_sub (float64_t , float64_t)
Referenced by fsub_d().
f64_to_extF80M()
void f64_to_extF80M (float64_t , extFloat80_t *)
f64_to_f128M()
void f64_to_f128M (float64_t , float128_t *)
f64_to_f16()
float16_t f64_to_f16 (float64_t)
f64_to_f32()
float32_t f64_to_f32 (float64_t)
Referenced by fconv_d2f().
f64_to_i32()
int_fast32_t f64_to_i32 (float64_t , uint_fast8_t , bool)
Referenced by fcvt_64_32().
f64_to_i32_r_minMag()
int_fast32_t f64_to_i32_r_minMag (float64_t , bool)
f64_to_i64()
int_fast64_t f64_to_i64 (float64_t , uint_fast8_t , bool)
Referenced by fcvt_d().
f64_to_i64_r_minMag()
int_fast64_t f64_to_i64_r_minMag (float64_t , bool)
f64_to_ui32()
uint_fast32_t f64_to_ui32 (float64_t , uint_fast8_t , bool)
Referenced by fcvt_64_32().
f64_to_ui32_r_minMag()
uint_fast32_t f64_to_ui32_r_minMag (float64_t , bool)
f64_to_ui64()
uint_fast64_t f64_to_ui64 (float64_t , uint_fast8_t , bool)
Referenced by fcvt_d().
f64_to_ui64_r_minMag()
uint_fast64_t f64_to_ui64_r_minMag (float64_t , bool)
i32_to_extF80M()
void i32_to_extF80M (int32_t , extFloat80_t *)
i32_to_f128M()
void i32_to_f128M (int32_t , float128_t *)
i32_to_f16()
float16_t i32_to_f16 (int32_t)
i32_to_f32()
float32_t i32_to_f32 (int32_t)
Referenced by fcvt_s().
i32_to_f64()
float64_t i32_to_f64 (int32_t)
Referenced by fcvt_32_64().
i64_to_extF80M()
void i64_to_extF80M (int64_t , extFloat80_t *)
i64_to_f128M()
void i64_to_f128M (int64_t , float128_t *)
i64_to_f16()
float16_t i64_to_f16 (int64_t)
i64_to_f32()
float32_t i64_to_f32 (int64_t)
Referenced by fcvt_64_32().
i64_to_f64()
float64_t i64_to_f64 (int64_t)
Referenced by fcvt_d().
softfloat_raiseFlags()
void softfloat_raiseFlags (uint_fast8_t)
Referenced by fcmp_d(), fcmp_s(), fsel_d(), and fsel_s().
ui32_to_extF80M()
void ui32_to_extF80M (uint32_t , extFloat80_t *)
ui32_to_f128M()
void ui32_to_f128M (uint32_t , float128_t *)
ui32_to_f16()
float16_t ui32_to_f16 (uint32_t)
ui32_to_f32()
float32_t ui32_to_f32 (uint32_t)
Referenced by fcvt_s().
ui32_to_f64()
float64_t ui32_to_f64 (uint32_t)
Referenced by fcvt_32_64().
ui64_to_extF80M()
void ui64_to_extF80M (uint64_t , extFloat80_t *)
ui64_to_f128M()
void ui64_to_f128M (uint64_t , float128_t *)
ui64_to_f16()
float16_t ui64_to_f16 (uint64_t)
ui64_to_f32()
float32_t ui64_to_f32 (uint64_t)
Referenced by fcvt_64_32().
ui64_to_f64()
float64_t ui64_to_f64 (uint64_t)
Referenced by fcvt_d().
Variable Documentation
extF80_roundingPrecision
THREAD_LOCAL uint_fast8_t extF80_roundingPrecision
softfloat_detectTininess
THREAD_LOCAL uint_fast8_t softfloat_detectTininess
softfloat_exceptionFlags
THREAD_LOCAL uint_fast8_t softfloat_exceptionFlags
Referenced by fadd_d(), fadd_s(), fcmp_d(), fcmp_s(), fcvt_32_64(), fcvt_64_32(), fcvt_d(), fcvt_s(), fdiv_d(), fdiv_s(), fget_flags(), fmadd_d(), fmadd_s(), fmul_d(), fmul_s(), fsel_d(), fsel_s(), fsqrt_d(), fsqrt_s(), fsub_d(), and fsub_s().
softfloat_roundingMode
THREAD_LOCAL uint_fast8_t softfloat_roundingMode
Referenced by fadd_d(), fadd_s(), fconv_d2f(), fconv_f2d(), fdiv_d(), fdiv_s(), fmadd_d(), fmadd_s(), fmul_d(), fmul_s(), fsqrt_d(), fsqrt_s(), fsub_d(), and fsub_s().